import { test, expect } from '@playwright/test'

test('published COMET source selection, LOS value and 323 real epochs survive reload', async ({ page, request, isMobile }) => {
  test.skip(!process.env.FORUDID_COMET_TESTS, 'Requires the verified and published COMET Varamin source')
  const errors: string[] = [], tiles: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('response', response => { if (response.url().includes('/tiles/') && response.ok()) tiles.push(response.url()) })
  const catalog = await request.get('/api/v1/products?aoi=varamin-comet')
  expect(catalog.ok(), await catalog.text()).toBe(true)
  const product = (await catalog.json()).find((p: { kind: string }) => p.kind === 'velocity_los')
  await page.goto('/map')
  if (isMobile) await page.locator('.mobile-layer-button').click()
  await page.getByRole('combobox', { name: 'محدودهٔ منبع تغییرشکل' }).selectOption('varamin-comet')
  await expect(page.getByRole('combobox', { name: 'انتخاب محصول', exact: true })).toContainText('COMET Varamin')
  if (isMobile) await page.locator('.sheet-close').click()
  await expect(page).toHaveURL(/aoi=varamin-comet/)
  await expect.poll(() => tiles.some(url => url.includes(product.assets.find((a: { role: string }) => a.role === 'data').id))).toBe(true)
  const search = page.getByRole('textbox', { name: 'جست‌وجوی شهر یا مختصات' })
  await search.fill('51.70033, 35.3')
  await search.press('Enter')
  await page.getByRole('button', { name: 'بررسی نقطهٔ مرکز نقشه' }).click()
  await expect(page).toHaveURL(/orbit=ascending/)
  const point = await request.get(`/api/v1/points/summary?product_id=${product.id}&lon=51.70033&lat=35.3`)
  expect(point.ok()).toBe(true)
  const expected = (await point.json()).measurement.value * 1000
  await expect(page.locator('.point-values strong')).toHaveText(expected.toLocaleString('fa-IR', { minimumFractionDigits: 1, maximumFractionDigits: 1 }))
  await expect(page.locator('.point-values')).toContainText('ارائه نشده')
  await expect(page.locator('.chart canvas').first()).toBeVisible()
  await page.locator('.series-table summary').click()
  await expect(page.locator('.maplibregl-ctrl-attrib')).not.toHaveAttribute('open', '')
  const legendBox = await page.locator('.legend').boundingBox()
  const searchBox = await page.locator('.map-place-search').boundingBox()
  expect(legendBox!.y).toBeGreaterThanOrEqual(searchBox!.y + searchBox!.height)
  await expect(page.locator('.series-table tbody tr')).toHaveCount(323)
  await expect(page.locator('.series-table tbody tr').last()).toContainText('2026-07-31')
  await page.locator('.series-table summary').click()
  await page.locator('.point-panel').evaluate(element => { element.scrollTop = 0 })
  await page.screenshot({ path: `/tmp/forudid-qa/comet-${isMobile ? 'mobile' : 'desktop'}.png` })
  await page.reload()
  await expect(page.locator('.chart canvas').first()).toBeVisible()
  await expect(page).toHaveURL(new RegExp(product.id))
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(errors).toEqual([])
})

test('COMET population selection links to the matching regional dashboard', async ({ page, isMobile }) => {
  test.skip(!process.env.FORUDID_COMET_TESTS, 'Requires the published real COMET population analyses')
  await page.goto('/map?aoi=varamin-comet&mode=population&layer=velocity_los&orbit=ascending')
  if (isMobile) await page.locator('.mobile-layer-button').click()
  await expect(page.getByTestId('population-covered').filter({ visible: true })).toHaveText('۱٬۶۵۷٬۲۳۹')
  await page.getByRole('link', { name: 'داشبورد کامل محدوده و زیرساخت' }).click()
  await expect(page).toHaveURL(/aoi=varamin-comet/)
  await expect(page.getByRole('combobox', { name: 'محدودهٔ منبع تغییرشکل' })).toHaveValue('varamin-comet')
  await page.getByRole('combobox', { name: 'محدوده', exact: true }).selectOption('637d5b9a-e103-54e0-8379-60beb1b21b40')
  await expect(page.getByTestId('population-covered')).toHaveText('۱٬۶۳۶٬۶۶۲')
  await expect(page.getByText('ellipsoid-cell-overlap-2', { exact: true })).toBeAttached()
  await page.reload()
  await expect(page.getByTestId('population-covered')).toHaveText('۱٬۶۳۶٬۶۶۲')
  await expect(page.getByText(/نرخ در راستای دید ماهواره/)).toBeVisible()
  await page.getByRole('button', { name: 'ساخت گزارش غربالگری فارسی', exact: true }).click()
  await expect(page.getByText('گزارش کامل به تحلیل منتشرشدهٔ جمعیت، راه‌آهن و راه برای همین منبع و محدوده نیاز دارد.')).toBeVisible()
})
