"""persist versioned line exposure"""

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

revision = "89a3ce782491"
down_revision = "f090827c07b9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analysis_methods",
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("definition", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('experimental','review','validated','deprecated')", name="method_status"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version"),
    )
    op.create_table(
        "analysis_runs",
        sa.Column("method_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("source_version_id", sa.Uuid(), nullable=False),
        sa.Column("signature", sa.String(length=64), nullable=False),
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("expected_assets", sa.Integer(), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("signature ~ '^[0-9a-f]{64}$'", name="analysis_signature"),
        sa.CheckConstraint("status IN ('processing','published','failed')", name="analysis_status"),
        sa.ForeignKeyConstraint(
            ["method_id"],
            ["analysis_methods.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_version_id"],
            ["source_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("signature"),
    )
    op.create_index(
        op.f("ix_analysis_runs_product_id"), "analysis_runs", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_analysis_runs_source_version_id"),
        "analysis_runs",
        ["source_version_id"],
        unique=False,
    )
    op.create_table(
        "asset_exposure_summaries",
        sa.Column("analysis_run_id", sa.Uuid(), nullable=False),
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("total_length_m", sa.Float(), nullable=False),
        sa.Column("valid_length_m", sa.Float(), nullable=False),
        sa.Column("coverage_fraction", sa.Float(), nullable=False),
        sa.Column("segment_count", sa.Integer(), nullable=False),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("profile_key", sa.String(), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("coverage_fraction BETWEEN 0 AND 1", name="exposure_coverage"),
        sa.ForeignKeyConstraint(
            ["analysis_run_id"],
            ["analysis_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("analysis_run_id", "asset_id", name="exposure_summary_identity"),
        sa.UniqueConstraint("profile_key"),
    )
    op.create_index(
        op.f("ix_asset_exposure_summaries_analysis_run_id"),
        "asset_exposure_summaries",
        ["analysis_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_asset_exposure_summaries_asset_id"),
        "asset_exposure_summaries",
        ["asset_id"],
        unique=False,
    )
    op.create_table(
        "exposure_segments",
        sa.Column("summary_id", sa.Uuid(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("start_chainage_m", sa.Float(), nullable=False),
        sa.Column("end_chainage_m", sa.Float(), nullable=False),
        sa.Column("band_index", sa.Integer(), nullable=True),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(geometry_type="LINESTRING", srid=4326, spatial_index=False),
            nullable=False,
        ),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("ST_IsValid(geom) AND NOT ST_IsEmpty(geom)", name="segment_geometry"),
        sa.CheckConstraint(
            "end_chainage_m > start_chainage_m AND start_chainage_m >= 0", name="segment_chainage"
        ),
        sa.ForeignKeyConstraint(
            ["summary_id"],
            ["asset_exposure_summaries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("summary_id", "ordinal", name="exposure_segment_identity"),
    )
    op.create_index(
        "idx_exposure_segments_geom",
        "exposure_segments",
        ["geom"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_index(
        op.f("ix_exposure_segments_summary_id"), "exposure_segments", ["summary_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    if op.get_bind().scalar(sa.text("SELECT EXISTS (SELECT 1 FROM analysis_runs)")):
        raise RuntimeError("Exposure runs exist; preserve them before downgrading")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_exposure_segments_summary_id"), table_name="exposure_segments")
    op.drop_index(
        "idx_exposure_segments_geom", table_name="exposure_segments", postgresql_using="gist"
    )
    op.drop_table("exposure_segments")
    op.drop_index(
        op.f("ix_asset_exposure_summaries_asset_id"), table_name="asset_exposure_summaries"
    )
    op.drop_index(
        op.f("ix_asset_exposure_summaries_analysis_run_id"), table_name="asset_exposure_summaries"
    )
    op.drop_table("asset_exposure_summaries")
    op.drop_index(op.f("ix_analysis_runs_source_version_id"), table_name="analysis_runs")
    op.drop_index(op.f("ix_analysis_runs_product_id"), table_name="analysis_runs")
    op.drop_table("analysis_runs")
    op.drop_table("analysis_methods")
    # ### end Alembic commands ###
