"""register versioned administrative regions"""

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

revision = "f478982ff999"
down_revision = "0e9e1d6772d9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "regions",
        sa.Column("source_version_id", sa.Uuid(), nullable=False),
        sa.Column("name_en", sa.String(), nullable=False),
        sa.Column("name_fa", sa.String(), nullable=False),
        sa.Column("source_code", sa.String(), nullable=True),
        sa.Column("area_m2", sa.Float(), nullable=False),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="MULTIPOLYGON", srid=4326, spatial_index=False
            ),
            nullable=False,
        ),
        sa.Column("bbox", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("properties", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("ST_IsValid(geom) AND NOT ST_IsEmpty(geom)", name="region_geometry"),
        sa.CheckConstraint("area_m2 > 0", name="region_area"),
        sa.ForeignKeyConstraint(
            ["source_version_id"],
            ["source_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_version_id", "name_en", name="region_source_name"),
    )
    op.create_index("idx_regions_geom", "regions", ["geom"], unique=False, postgresql_using="gist")
    op.create_index(
        op.f("ix_regions_source_version_id"), "regions", ["source_version_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    if op.get_bind().scalar(sa.text("SELECT EXISTS (SELECT 1 FROM regions)")):
        raise RuntimeError("Regions exist; preserve source data before downgrading")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_regions_source_version_id"), table_name="regions")
    op.drop_index("idx_regions_geom", table_name="regions", postgresql_using="gist")
    op.drop_table("regions")
    # ### end Alembic commands ###
